TITLE_SAVE_MODULE_AS = 'Сохранить модуль как ...';
TITLE_OPEN_FILE = 'Открыть файл';
TITLE_SAVE_AS = 'Сохранить как ...';

MSG_INCORRECT_VALUE = 'Неверное значение';
MSG_MODULE_NAME_MUST_LEAST = 'Название модуля должно состоять минимум из 3-х символов';
MSG_CONFIRMATION = 'Подтверждение';
MSG_MODULE_ALREADY_EXISTS = 'Модуль с таким именем уже существует, заменить?';
MSG_FORMAT_CODE = 'Форматировать код';
MSG_SAVE_CHANGES = 'Сохранить изменения в файле';
MSG_PROCESS_IS_STARTED = 'Запущен процесс';
MSG_INTERRUPT_EXECUTION = 'Прервать выполнение';
MSG_GOING_ASSEMBLED = 'идет сборка, это займет около минуты';
MSG_SUCCESSFULLY_ASSEMBLED = 'Проект успешно собран';
MSG_VERSION = 'Версия';
MSG_SIZE = 'Размер';
MSG_PLATFORM = 'Платформа';

ERR_SAVE_NOTES_FILE = 'Не удалось сохранить файл заметок';
ERR_NOT_AVAILABLE_NO_OPEN_PROJECT = 'Недоступно, нет открытого проекта';
ERR_LOAD_NOTES = 'Не удалось загрузить файл заметок';
ERR_FAILED_SAVE = 'Не удалось сохранить';
ERR_FAILED_DOWNLOAD = 'Не удалось загрузить';
ERR_FAILDED_BUILD_APK = 'Не удалось собрать APK файл, подробности';
ERR_ANT_COMPLETED_WORK = 'Ant завершил работу, подробности';

STBAR_MODIFIED = 'Изменён';
FILTER_ALL_FILES = 'Все файлы';

CAPTION_CREATE_MODULE = 'Создать модуль';
CAPTION_OPEN = 'Открыть';
CAPTION_SAVE = 'Сохранить';
CAPTION_CLOSE_EDITOR_FILE = 'Закрыть файл редактора';
CAPTION_SAVE_ALL = 'Сохранить все';
CAPTION_BUILD_APK = 'Собрать APK';
CAPTION_BUILD = 'Собрать';
CAPTION_COMPILE = 'Компилировать';
CAPTION_KILL_PROC = 'Завершить процесс';
CAPTION_RUN = 'Запустить';
CAPTION_MESSAGES = 'Сообщения';
CAPTION_NOTES = 'Заметки';
CAPTION_FILES = 'Файлы';
CAPTION_SETTINGS = 'Параметры';
CAPTION_DATETIME = 'Дата и время';
CAPTION_USERNAME = 'Имя пользователя';
CAPTION_COMPACT_VIEW = 'Компактный режим';
CAPTION_EXPORT_HTML = 'Экспортировать в HTML';
CAPTION_CREATE_PROJ = 'Создать проект';
CAPTION_CLOSE_TAB = 'Закрыть вкладку';
CAPTION_CLOSE_OTHER_TABS = 'Закрыть другие вкладки';

CAPTION_VIEW = '&Вид';
CAPTION_CODE = '&Код';
CAPTION_OPTIONS = '&Настройка';
CAPTION_HELP = '&Справка';
CAPTION_DOCS = 'Документация';
CAPTION_JAVA_LIBS = 'Java библиотеки';
CAPTION_EXAMPLES = 'Примеры';
CAPTION_MACROS = 'Макросы IDE';
CAPTION_ABOUT= 'О программе';
CAPTION_EXIT = 'Выход';
CAPTION_INS_GENERAL = 'Вставить общее';
CAPTION_JCF = 'Форматирование кода JEDI';
CAPTION_CURRENT_TAB = 'Текущая вкладка редактора';
CAPTION_IDE_SETTINGS = 'Настроить AMPASIDE';

